package httpapi

import("encoding/json";"fmt";"net/http";"strings";"time";"github.com/palmid3v/financial-d3v-palmid3v/internal/application";"github.com/palmid3v/financial-d3v-palmid3v/internal/domain")
const ownerHeader="X-Owner-ID"
type Server struct{accounts *application.AccountService;transactions *application.TransactionService;firebaseReady bool}
func NewServer(a *application.AccountService,t *application.TransactionService,ready bool)*Server{return &Server{accounts:a,transactions:t,firebaseReady:ready}}
func(s *Server)Handler()http.Handler{mux:=http.NewServeMux();mux.HandleFunc("GET /health",s.health);mux.HandleFunc("GET /ready",s.ready);mux.HandleFunc("POST /api/v1/accounts",s.createAccount);mux.HandleFunc("GET /api/v1/accounts",s.listAccounts);mux.HandleFunc("GET /api/v1/accounts/{accountID}",s.getAccount);mux.HandleFunc("GET /api/v1/accounts/{accountID}/balance",s.getBalance);mux.HandleFunc("POST /api/v1/transactions",s.createTransaction);mux.HandleFunc("GET /api/v1/transactions",s.listTransactions);mux.HandleFunc("GET /api/v1/transactions/{transactionID}",s.getTransaction);return requestIDMiddleware(loggingMiddleware(mux))}
func(s *Server)health(w http.ResponseWriter,_ *http.Request){writeJSON(w,http.StatusOK,map[string]any{"status":"ok","service":"financial-d3v-api"})}
func(s *Server)ready(w http.ResponseWriter,_ *http.Request){code:=http.StatusOK;status:="ready";if !s.firebaseReady{code=http.StatusServiceUnavailable;status="degraded"};writeJSON(w,code,map[string]any{"status":status,"service":"financial-d3v-api","dependencies":map[string]bool{"firebase":s.firebaseReady}})}
func(s *Server)servicesReady(w http.ResponseWriter)bool{if s.accounts==nil||s.transactions==nil{writeError(w,http.StatusServiceUnavailable,"financial services are unavailable; enable Firebase first");return false};return true}
func requireOwner(w http.ResponseWriter,r *http.Request)(string,bool){id:=strings.TrimSpace(r.Header.Get(ownerHeader));if id==""{writeError(w,http.StatusBadRequest,fmt.Sprintf("%s header is required until Firebase Auth is implemented",ownerHeader));return "",false};return id,true}
func decodeJSON(w http.ResponseWriter,r *http.Request,v any)bool{defer r.Body.Close();d:=json.NewDecoder(r.Body);d.DisallowUnknownFields();if err:=d.Decode(v);err!=nil{writeError(w,http.StatusBadRequest,"invalid JSON payload");return false};return true}

type accountRequest struct{Name string `json:"name"`;Type string `json:"type"`;Currency string `json:"currency"`;OpeningMinor int64 `json:"openingMinorUnits"`}
type accountResponse struct{ID string `json:"id"`;Name string `json:"name"`;Type string `json:"type"`;Currency string `json:"currency"`;OpeningMinor int64 `json:"openingMinorUnits"`;CreatedAt string `json:"createdAt"`}
func(s *Server)createAccount(w http.ResponseWriter,r *http.Request){if !s.servicesReady(w){return};owner,ok:=requireOwner(w,r);if !ok{return};var req accountRequest;if !decodeJSON(w,r,&req){return};a,err:=domain.NewAccount(newID(),owner,strings.TrimSpace(req.Name),domain.AccountType(req.Type),domain.Money{MinorUnits:req.OpeningMinor,Currency:strings.ToUpper(strings.TrimSpace(req.Currency))},time.Now().UTC());if err!=nil{writeError(w,statusForError(err),err.Error());return};if err:=s.accounts.Create(r.Context(),a);err!=nil{writeError(w,statusForError(err),err.Error());return};writeJSON(w,http.StatusCreated,toAccountResponse(a))}
func(s *Server)listAccounts(w http.ResponseWriter,r *http.Request){if !s.servicesReady(w){return};owner,ok:=requireOwner(w,r);if !ok{return};values,err:=s.accounts.List(r.Context(),owner);if err!=nil{writeError(w,statusForError(err),err.Error());return};out:=make([]accountResponse,0,len(values));for _,v:=range values{out=append(out,toAccountResponse(v))};writeJSON(w,http.StatusOK,out)}
func(s *Server)getAccount(w http.ResponseWriter,r *http.Request){if !s.servicesReady(w){return};owner,ok:=requireOwner(w,r);if !ok{return};v,err:=s.accounts.Get(r.Context(),owner,r.PathValue("accountID"));if err!=nil{writeError(w,statusForError(err),err.Error());return};writeJSON(w,http.StatusOK,toAccountResponse(v))}
func(s *Server)getBalance(w http.ResponseWriter,r *http.Request){if !s.servicesReady(w){return};owner,ok:=requireOwner(w,r);if !ok{return};id:=r.PathValue("accountID");if _,err:=s.accounts.Get(r.Context(),owner,id);err!=nil{writeError(w,statusForError(err),err.Error());return};b,err:=s.accounts.Balance(r.Context(),owner,id);if err!=nil{writeError(w,statusForError(err),err.Error());return};writeJSON(w,http.StatusOK,map[string]any{"accountId":id,"currency":b.Currency,"minorUnits":b.MinorUnits})}

type transactionRequest struct{AccountID string `json:"accountId"`;Type string `json:"type"`;MinorUnits int64 `json:"minorUnits"`;Currency string `json:"currency"`;CategoryID string `json:"categoryId"`;TransferID string `json:"transferId"`;Description string `json:"description"`;OccurredAt string `json:"occurredAt"`}
type transactionResponse struct{ID string `json:"id"`;AccountID string `json:"accountId"`;Type string `json:"type"`;MinorUnits int64 `json:"minorUnits"`;Currency string `json:"currency"`;CategoryID string `json:"categoryId,omitempty"`;TransferID string `json:"transferId,omitempty"`;Description string `json:"description,omitempty"`;OccurredAt string `json:"occurredAt"`;CreatedAt string `json:"createdAt"`}
func(s *Server)createTransaction(w http.ResponseWriter,r *http.Request){if !s.servicesReady(w){return};owner,ok:=requireOwner(w,r);if !ok{return};var req transactionRequest;if !decodeJSON(w,r,&req){return};occurred,err:=time.Parse(time.RFC3339,req.OccurredAt);if err!=nil{writeError(w,http.StatusBadRequest,"occurredAt must be RFC3339");return};t,err:=domain.NewTransaction(newID(),owner,strings.TrimSpace(req.AccountID),domain.TransactionType(req.Type),domain.Money{MinorUnits:req.MinorUnits,Currency:strings.ToUpper(strings.TrimSpace(req.Currency))},occurred);if err!=nil{writeError(w,statusForError(err),err.Error());return};t.CategoryID=strings.TrimSpace(req.CategoryID);t.TransferID=strings.TrimSpace(req.TransferID);t.Description=strings.TrimSpace(req.Description);if err:=s.transactions.Create(r.Context(),t);err!=nil{writeError(w,statusForError(err),err.Error());return};writeJSON(w,http.StatusCreated,toTransactionResponse(t))}
func(s *Server)listTransactions(w http.ResponseWriter,r *http.Request){if !s.servicesReady(w){return};owner,ok:=requireOwner(w,r);if !ok{return};var values []domain.Transaction;var err error;if id:=strings.TrimSpace(r.URL.Query().Get("accountId"));id!=""{values,err=s.transactions.ListByAccount(r.Context(),owner,id)}else{start,end:=r.URL.Query().Get("start"),r.URL.Query().Get("end");if start==""||end==""{writeError(w,http.StatusBadRequest,"provide accountId or both start and end");return};a,e1:=time.Parse(time.RFC3339,start);b,e2:=time.Parse(time.RFC3339,end);if e1!=nil||e2!=nil{writeError(w,http.StatusBadRequest,"start and end must be RFC3339");return};p,e:=domain.NewFinancialPeriod(a,b);if e!=nil{writeError(w,http.StatusBadRequest,e.Error());return};values,err=s.transactions.ListByPeriod(r.Context(),owner,p)};if err!=nil{writeError(w,statusForError(err),err.Error());return};out:=make([]transactionResponse,0,len(values));for _,v:=range values{out=append(out,toTransactionResponse(v))};writeJSON(w,http.StatusOK,out)}
func(s *Server)getTransaction(w http.ResponseWriter,r *http.Request){if !s.servicesReady(w){return};owner,ok:=requireOwner(w,r);if !ok{return};v,err:=s.transactions.Get(r.Context(),owner,r.PathValue("transactionID"));if err!=nil{writeError(w,statusForError(err),err.Error());return};writeJSON(w,http.StatusOK,toTransactionResponse(v))}
func toAccountResponse(v domain.Account)accountResponse{return accountResponse{ID:v.ID,Name:v.Name,Type:string(v.Type),Currency:v.Currency,OpeningMinor:v.OpeningBalance.MinorUnits,CreatedAt:v.CreatedAt.Format(time.RFC3339)}}
func toTransactionResponse(v domain.Transaction)transactionResponse{return transactionResponse{ID:v.ID,AccountID:v.AccountID,Type:string(v.Type),MinorUnits:v.Amount.MinorUnits,Currency:v.Amount.Currency,CategoryID:v.CategoryID,TransferID:v.TransferID,Description:v.Description,OccurredAt:v.OccurredAt.Format(time.RFC3339),CreatedAt:v.CreatedAt.Format(time.RFC3339)}}
