import { useEffect, useMemo, useState } from "react";
import { api } from "./api";

const money = (m) => new Intl.NumberFormat("es-CO",{style:"currency",currency:m?.currency||"COP",maximumFractionDigits:0}).format((Number(m?.minorUnits)||0)/100);
const toMinor = (value) => Math.round(Number(value||0)*100);
const today = new Date();
const monthStart = new Date(today.getFullYear(),today.getMonth(),1).toISOString();
const monthEnd = new Date(today.getFullYear(),today.getMonth()+1,1).toISOString();

const nav = [
  ["dashboard","Overview","⌂"],["transactions","Transactions","↕"],["accounts","Accounts","▣"],
  ["budget","Budget","◫"],["savings","Savings","◎"],["debts","Debts","◇"],
  ["net-worth","Net worth","◆"],["education","Education","?"]
];
const accountTypes = [["cash","Cash"],["bank","Bank"],["credit","Credit"],["investment","Investment"],["other","Other"]];
const transactionTypes = [["expense","Expense"],["income","Income"],["transfer","Transfer"]];

function Button({children,onClick,primary=false,disabled=false,type="button"}){return <button type={type} disabled={disabled} onClick={onClick} className={primary?"button primary":"button"}>{children}</button>}
function Input({label,...props}){return <label className="field"><span>{label}</span><input {...props}/></label>}
function Select({label,children,...props}){return <label className="field"><span>{label}</span><select {...props}>{children}</select></label>}
function Panel({children,className=""}){return <section className={"panel "+className}>{children}</section>}
function Loading(){return <div className="state">Loading your financial workspace…</div>}
function Empty({title,text}){return <div className="empty"><b>+</b><h3>{title}</h3><p>{text}</p></div>}
function Notice({error,onRetry}){return error?<div className="notice error"><b>Something needs attention.</b><span>{error}</span>{onRetry&&<Button onClick={onRetry}>Try again</Button>}</div>:null}
function Metric({label,value,detail,icon}){return <article className="metric"><div><small>{label}</small><span>{icon}</span></div><strong>{value}</strong><em>{detail}</em></article>}

function Sidebar({active,setActive}){return <aside className="sidebar"><div className="brand"><b className="brand-mark">F</b><div><strong>Financial-D3v</strong><small>Personal finance</small></div></div><span className="label">Workspace</span><nav>{nav.map(([key,label,icon])=><button key={key} onClick={()=>setActive(key)} className={active===key?"nav active":"nav"}><i>{icon}</i>{label}</button>)}</nav><div className="side-bottom"><div className="privacy"><span/><div><b>Private workspace</b><small>Your data stays yours.</small></div></div><small className="signature">PALMI-D3V · v0.1</small></div></aside>}
function MobileNav({active,setActive}){return <nav className="mobile-nav">{nav.slice(0,5).map(([key,label,icon])=><button key={key} onClick={()=>setActive(key)} className={active===key?"active":""}><i>{icon}</i><small>{label}</small></button>)}</nav>}
function Header({active,refresh,loading}){const label=nav.find(x=>x[0]===active)?.[1]||"Overview";return <header className="topbar"><div><small>Financial-D3v <b>/</b> {label}</small><h1>{label}</h1></div><div className="top-actions"><span className="status"><i/> Local mode</span><Button onClick={refresh}>{loading?"Refreshing…":"Refresh"}</Button><b className="avatar">P</b></div></header>}

function Dashboard({data,setActive}){
 const s=data?.summary;
 const income=Number(s?.income?.minorUnits)||0, expenses=Number(s?.expenses?.minorUnits)||0, max=Math.max(income,expenses,1);
 return <><section className="hero"><div><small>Your financial picture</small><h2>Make your money <em>make sense.</em></h2><p>Record the movement, understand the state, then decide what comes next.</p></div><Button primary onClick={()=>setActive("transactions")}>＋ Record movement</Button></section>
 <div className="metrics"><Metric label="Income" value={money(s?.income)} detail="Money in this month" icon="↗"/><Metric label="Expenses" value={money(s?.expenses)} detail="Money out this month" icon="↘"/><Metric label="Net cash flow" value={money(s?.netCashFlow)} detail="Income minus expenses" icon="≈"/><Metric label="Net worth" value={money(s?.netWorth?.net)} detail="Assets minus liabilities" icon="◆"/></div>
 <div className="two-col"><Panel><div className="panel-head"><div><small>Monthly cash flow</small><h2>Where your money moved</h2></div></div><div className="flow-row">{[["Income",income,s?.income,"↗"],["Expenses",expenses,s?.expenses,"↘"]].map(([label,value,amount,icon])=><div className="flow" key={label}><div><label>{label}</label><b>{money(amount)}</b></div><div className="track"><i style={{width:`${Math.max((value/max)*100,value?8:0)}%`}}/></div></div>)}</div></Panel><Panel className="education"><span className="badge">Learn</span><small>Financial education</small><h2>Your numbers should teach you something.</h2><p>Financial-D3v connects the number with the reason behind it, then turns that understanding into your next action.</p><div>FACT <b>→</b> CALCULATION <b>→</b> INTERPRETATION <b>→</b> ACTION</div></Panel></div>
 <section><div className="section-head"><div><small>Next actions</small><h2>Keep the loop moving</h2></div></div><div className="actions">{[["transactions","Add transaction","Record money in or out"],["accounts","Manage accounts","See where money lives"],["budget","Review budget","Compare planned vs actual"]].map(([key,title,detail])=><button key={key} onClick={()=>setActive(key)}><b>+</b><div><strong>{title}</strong><small>{detail}</small></div><i>↗</i></button>)}</div></section></>
}

function Transactions({ownerId}){
 const [accounts,setAccounts]=useState([]),[categories,setCategories]=useState([]),[items,setItems]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [form,setForm]=useState({type:"expense",amount:"",accountId:"",categoryId:"",description:"",occurredAt:new Date().toISOString().slice(0,16)});
 const load=async()=>{setLoading(true);setError("");try{const [a,c,t]=await Promise.all([api("/api/v1/accounts",{ownerId}),api("/api/v1/categories",{ownerId}),api(`/api/v1/transactions?start=${encodeURIComponent(monthStart)}&end=${encodeURIComponent(monthEnd)}`,{ownerId})]);setAccounts(a||[]);setCategories(c||[]);setItems(t||[]);if(!form.accountId&&a?.[0])setForm(f=>({...f,accountId:a[0].id||a[0].ID}))}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const filtered=categories.filter(c=>(c.kind||c.Kind)===form.type);
 const submit=async(e)=>{e.preventDefault();setSaving(true);setError("");setMessage("");try{const account=accounts.find(a=>(a.id||a.ID)===form.accountId);if(!account)throw new Error("Select an account.");const currency=account.currency||account.Currency||"COP";await api("/api/v1/transactions",{ownerId,method:"POST",body:{accountId:form.accountId,type:form.type,minorUnits:toMinor(form.amount),currency,categoryId:form.type==="transfer"?"":form.categoryId,description:form.description,occurredAt:new Date(form.occurredAt).toISOString()}});setForm(f=>({...f,amount:"",description:""}));setMessage("Transaction recorded.");await load()}catch(e){setError(e.message)}finally{setSaving(false)}};
 return <div className="workspace"><div className="module-head"><div><small>Record → Categorize</small><h2>Transactions</h2><p>Capture money in, money out, and transfers without slowing down the workflow.</p></div></div><div className="two-col"><Panel><div className="panel-head"><div><small>Quick entry</small><h3>Record a movement</h3></div></div><form onSubmit={submit} className="form-grid"><Select label="Type" value={form.type} onChange={e=>setForm({...form,type:e.target.value,categoryId:""})}>{transactionTypes.map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select><Input label="Amount" type="number" min="0.01" step="0.01" required value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><Select label="Account" value={form.accountId} onChange={e=>setForm({...form,accountId:e.target.value})}><option value="">Select account</option>{accounts.map(a=><option key={a.id||a.ID} value={a.id||a.ID}>{a.name||a.Name}</option>)}</Select>{form.type!=="transfer"&&<Select label="Category" value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Select category</option>{filtered.map(c=><option key={c.id||c.ID} value={c.id||c.ID}>{c.name||c.Name}</option>)}</Select>}<Input label="Date" type="datetime-local" value={form.occurredAt} onChange={e=>setForm({...form,occurredAt:e.target.value})}/><Input label="Description" placeholder="Optional note" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><div className="form-actions"><Button primary disabled={saving} type="submit">{saving?"Saving…":"Record transaction"}</Button></div></form><Notice error={error}/>{message&&<div className="notice success">{message}</div>}</Panel><Panel><div className="panel-head"><div><small>This month</small><h3>Recent movements</h3></div></div>{loading?<Loading/>:items.length===0?<Empty title="No transactions yet" text="Record your first movement and the dashboard will start learning from your ledger."/>:<div className="list">{items.slice().reverse().map(t=><div className="list-row" key={t.id||t.ID}><div><b>{t.description||t.Description||"Transaction"}</b><small>{t.type||t.Type} · {new Date(t.occurredAt||t.OccurredAt).toLocaleDateString("es-CO")}</small></div><strong className={(t.type||t.Type)==="expense"?"negative":"positive"}>{(t.type||t.Type)==="expense"?"−":"+"}{money(t.amount||t.Amount)}</strong></div>)}</div>}</Panel></div></div>
}

function Accounts({ownerId}){
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[form,setForm]=useState({name:"",type:"bank",currency:"COP",opening:""});
 const load=async()=>{setLoading(true);setError("");try{const accounts=await api("/api/v1/accounts",{ownerId})||[];const enriched=await Promise.all(accounts.map(async a=>{const accountId=a.id||a.ID;try{return {...a,balance:await api(`/api/v1/accounts/${accountId}/balance`,{ownerId})}}catch{return a}}));setItems(enriched)}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const submit=async(e)=>{e.preventDefault();setSaving(true);setError("");try{await api("/api/v1/accounts",{ownerId,method:"POST",body:{name:form.name,type:form.type,currency:form.currency.toUpperCase(),openingMinorUnits:toMinor(form.opening)}});setForm({name:"",type:"bank",currency:"COP",opening:""});await load()}catch(e){setError(e.message)}finally{setSaving(false)}};
 return <div className="workspace"><div className="module-head"><div><small>Foundation</small><h2>Accounts</h2><p>Know where your money lives. Balances remain derived from the authoritative ledger.</p></div></div><div className="two-col"><Panel><div className="panel-head"><div><small>New account</small><h3>Add an account</h3></div></div><form onSubmit={submit} className="form-grid"><Input label="Name" placeholder="Main bank account" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Select label="Type" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{accountTypes.map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select><Input label="Currency" maxLength="3" value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}/><Input label="Opening balance" type="number" step="0.01" value={form.opening} onChange={e=>setForm({...form,opening:e.target.value})}/><div className="form-actions"><Button primary disabled={saving} type="submit">{saving?"Saving…":"Create account"}</Button></div></form><Notice error={error}/></Panel><Panel><div className="panel-head"><div><small>Your money</small><h3>Accounts</h3></div></div>{loading?<Loading/>:items.length===0?<Empty title="No accounts yet" text="Create your first cash or bank account to start recording transactions."/>:<div className="account-grid">{items.map(a=><article className="account-card" key={a.id||a.ID}><div><span className="badge">{a.type||a.Type}</span><small>{a.currency||a.Currency}</small></div><h3>{a.name||a.Name}</h3><strong>{money(a.balance||a.Balance||a.openingBalance||a.OpeningBalance)}</strong><p>Opening balance {money(a.openingBalance||a.OpeningBalance)}</p></article>)}</div>}</Panel></div></div>
}

function Budget({ownerId}){
 const [categories,setCategories]=useState([]),[budgets,setBudgets]=useState([]),[selected,setSelected]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[form,setForm]=useState({name:"Monthly budget",items:[{categoryId:"",limit:""}]});
 const load=async()=>{setLoading(true);setError("");try{const [c,b]=await Promise.all([api("/api/v1/categories",{ownerId}),api(`/api/v1/budgets?start=${encodeURIComponent(monthStart)}&end=${encodeURIComponent(monthEnd)}`,{ownerId})]);setCategories((c||[]).filter(x=>(x.kind||x.Kind)==="expense"));setBudgets(b||[])}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const setItem=(i,k,v)=>setForm(f=>({...f,items:f.items.map((x,n)=>n===i?{...x,[k]:v}:x)}));
 const createBudget=async(e)=>{e.preventDefault();setSaving(true);setError("");try{const items=form.items.filter(x=>x.categoryId&&Number(x.limit)>0).map(x=>({categoryId:x.categoryId,limitMinorUnits:toMinor(x.limit)}));if(!items.length)throw new Error("Add at least one expense category.");if(new Set(items.map(x=>x.categoryId)).size!==items.length)throw new Error("Each category can appear only once.");await api("/api/v1/budgets",{ownerId,method:"POST",body:{name:form.name,currency:"COP",startDate:monthStart,endDate:monthEnd,items}});setForm({name:"Monthly budget",items:[{categoryId:"",limit:""}]});await load()}catch(e){setError(e.message)}finally{setSaving(false)}};
 const open=async(b)=>{try{setSelected(await api(`/api/v1/budgets/${b.id||b.ID}/summary`,{ownerId}))}catch(e){setError(e.message)}};
 return <div className="workspace"><div className="module-head"><div><small>Plan → Understand</small><h2>Budget</h2><p>Set limits, then compare them with actual spending from the transaction ledger.</p></div></div><div className="two-col"><Panel><div className="panel-head"><div><small>Monthly plan</small><h3>Create a budget</h3></div></div><form onSubmit={createBudget} className="form-grid"><Input label="Budget name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><div className="budget-items">{form.items.map((item,index)=><div className="budget-input-row" key={index}><Select label={`Category ${index+1}`} required value={item.categoryId} onChange={e=>setItem(index,"categoryId",e.target.value)}><option value="">Select category</option>{categories.map(c=><option key={c.id||c.ID} value={c.id||c.ID}>{c.name||c.Name}</option>)}</Select><Input label="Limit" type="number" min="0.01" step="0.01" required value={item.limit} onChange={e=>setItem(index,"limit",e.target.value)}/></div>)}</div><div className="form-actions"><Button primary disabled={saving} type="submit">{saving?"Saving…":"Create budget"}</Button></div></form><Notice error={error}/></Panel><Panel><div className="panel-head"><div><small>Planned vs actual</small><h3>Budget overview</h3></div></div>{loading?<Loading/>:budgets.length===0?<Empty title="No budget yet" text="Create a monthly budget and give your expense categories a clear job."/>:<div className="list">{budgets.map(b=><button className="list-row clickable" key={b.id||b.ID} onClick={()=>open(b)}><div><b>{b.name||b.Name}</b><small>{b.currency||b.Currency}</small></div><strong>{money({minorUnits:(b.items||b.Items||[]).reduce((sum,item)=>sum+(item.limitMinorUnits||item.LimitMinorUnits||item.limit?.minorUnits||item.Limit?.MinorUnits||0),0),currency:b.currency||b.Currency||"COP"})}</strong></button>)}</div>}</Panel></div>{selected&&<Panel className="budget-detail"><div className="panel-head"><div><small>FACT → CALCULATION</small><h3>Budget summary</h3></div><Button onClick={()=>setSelected(null)}>Close</Button></div><div className="metrics"><Metric label="Planned" value={money(selected.totalLimit||selected.TotalLimit)} detail="Budget limit" icon="◫"/><Metric label="Spent" value={money(selected.totalSpent||selected.TotalSpent)} detail="Authoritative ledger" icon="↘"/><Metric label="Remaining" value={money(selected.totalRemaining||selected.TotalRemaining)} detail="Limit minus spent" icon="≈"/></div></Panel>}</div>
}

function NetWorth({ownerId}){const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=async()=>{setLoading(true);setError("");try{setData(await api("/api/v1/net-worth?currency=COP",{ownerId}))}catch(e){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);return <div className="workspace"><div className="module-head"><div><small>Understand → Review</small><h2>Net worth</h2><p>See your financial position from backend-authoritative assets and liabilities.</p></div></div>{loading?<Loading/>:error?<Notice error={error} onRetry={load}/>:<><div className="metrics"><Metric label="Net worth" value={money(data?.net)} detail="Assets minus liabilities" icon="◆"/><Metric label="Assets" value={money(data?.assets)} detail="Tracked assets" icon="↗"/><Metric label="Liabilities" value={money(data?.liabilities)} detail="All liabilities" icon="↘"/><Metric label="Debt" value={money(data?.debtLiabilities)} detail="Debt balance included" icon="◇"/></div><Panel className="education"><span className="badge">FACT → CALCULATION → INTERPRETATION → ACTION</span><p><b>Fact:</b> these values come from the financial position service.</p><p><b>Calculation:</b> net worth = assets − liabilities.</p><p><b>Interpretation:</b> the result is a snapshot, not a forecast.</p><p><b>Action:</b> review the components and keep the ledger current.</p></Panel></>}</div>}

function Education({ownerId}){const [cards,setCards]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=async()=>{setLoading(true);setError("");try{setCards(await api("/api/v1/education",{ownerId})||[])}catch(e){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);return <div className="workspace"><div className="module-head"><div><small>Learn → Adjust</small><h2>Education</h2><p>Learn financial concepts through explicit facts, calculations, interpretations and actions.</p></div></div>{loading?<Loading/>:error?<Notice error={error} onRetry={load}/>:cards.length===0?<Empty title="No education cards" text="Education content will appear here as the learning workspace evolves."/>:<div className="education-grid">{cards.map(card=><Panel className="education" key={card.id||card.ID}><span className="badge">{card.topic||card.Topic}</span><h3>{card.title||card.Title}</h3><div className="edu-step"><b>FACT</b><p>{card.fact||card.Fact}</p></div><div className="edu-step"><b>CALCULATION</b><p>{card.calculation||card.Calculation}</p></div><div className="edu-step"><b>INTERPRETATION</b><p>{card.interpretation||card.Interpretation}</p></div><div className="edu-step"><b>ACTION</b><p>{card.action||card.Action}</p></div></Panel>)}</div>}</div>}

function Placeholder({active,setActive}){const item=nav.find(n=>n[0]===active);return <div className="module"><small>Workspace</small><h2>{item?.[1]}</h2><p>This product surface is reserved for its validated workflow.</p><Panel className="empty"><b>{item?.[2]}</b><h3>{item?.[1]} is part of the financial learning loop.</h3><p>Continue with the next validated product iteration without changing the financial source of truth.</p><Button onClick={()=>setActive("dashboard")}>Back to overview</Button></Panel></div>}

export default function App(){
 const [active,setActive]=useState("dashboard"),[ownerId]=useState(localStorage.getItem("financial_owner")||"local-owner"),[data,setData]=useState(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const period=useMemo(()=>`start=${encodeURIComponent(monthStart)}&end=${encodeURIComponent(monthEnd)}&currency=COP`,[]);
 const load=async()=>{setLoading(true);setError("");try{setData(await api(`/api/v1/dashboard?${period}`,{ownerId}))}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{localStorage.setItem("financial_owner",ownerId);load()},[]);
 const content=active==="dashboard"?<Dashboard data={data} setActive={setActive}/>:active==="transactions"?<Transactions ownerId={ownerId}/>:active==="accounts"?<Accounts ownerId={ownerId}/>:active==="budget"?<Budget ownerId={ownerId}/>:active==="net-worth"?<NetWorth ownerId={ownerId}/>:active==="education"?<Education ownerId={ownerId}/>:<Placeholder active={active} setActive={setActive}/>;
 return <div className="shell"><Sidebar active={active} setActive={setActive}/><div className="main"><Header active={active} refresh={load} loading={loading}/><main>{active==="dashboard"?(loading?<Loading/>:error?<Notice error={error} onRetry={load}/>:content):content}<footer>Private by design · Financial-D3v · PALMI-D3V</footer></main></div><MobileNav active={active} setActive={setActive}/></div>
}