import {useEffect,useMemo,useState} from "react";
import {api} from "./api";

const money=(m)=>new Intl.NumberFormat("es-CO",{style:"currency",currency:m?.currency||"COP",maximumFractionDigits:0}).format((m?.minorUnits||0)/100);
const today=new Date(); const monthStart=new Date(today.getFullYear(),today.getMonth(),1).toISOString(); const nextMonth=new Date(today.getFullYear(),today.getMonth()+1,1).toISOString();

function Card({title,value,detail}){return <section className="rounded-2xl border border-zinc-800 bg-zinc-900/80 p-5 shadow-xl"><p className="text-sm text-zinc-400">{title}</p><p className="mt-2 text-2xl font-semibold tracking-tight">{value}</p>{detail&&<p className="mt-2 text-xs text-zinc-500">{detail}</p>}</section>}
function Nav({active,setActive}){return <nav className="flex gap-2 overflow-x-auto pb-2">{["dashboard","transactions","budget","savings","debts","net-worth"].map(x=><button key={x} onClick={()=>setActive(x)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm ${active===x?"bg-white text-zinc-950":"bg-zinc-900 text-zinc-400 hover:text-white"}`}>{x.replace("-"," ")}</button>)}</nav>}
function Dashboard({data}){const s=data?.summary;return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card title="Income" value={money(s?.income)}/><Card title="Expenses" value={money(s?.expenses)}/><Card title="Net cash flow" value={money(s?.netCashFlow)} detail="Income minus expenses"/><Card title="Net worth" value={money(s?.netWorth?.net)} detail="Assets minus liabilities"/></div>}
function App(){
 const [active,setActive]=useState("dashboard"),[ownerId,setOwnerId]=useState(localStorage.getItem("financial_owner")||"local-owner"),[currency]=useState("COP"),[data,setData]=useState(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const period=useMemo(()=>`start=${encodeURIComponent(monthStart)}&end=${encodeURIComponent(nextMonth)}&currency=${currency}`,[currency]);
 const load=async()=>{setLoading(true);setError("");try{setData(await api(`/api/v1/dashboard?${period}`,{ownerId}))}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{localStorage.setItem("financial_owner",ownerId);load()},[]);
 return <div className="min-h-screen bg-zinc-950 text-zinc-100"><header className="border-b border-zinc-900"><div className="mx-auto max-w-7xl px-4 py-5 sm:px-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.25em] text-zinc-500">PALMI-D3V</p><h1 className="mt-1 text-2xl font-bold">Financial-D3v</h1><p className="text-sm text-zinc-400">Record → Understand → Plan → Save → Review</p></div><button onClick={load} className="rounded-xl border border-zinc-700 px-4 py-2 text-sm hover:bg-zinc-900">Refresh</button></div><div className="mt-5"><Nav active={active} setActive={setActive}/></div></div></header><main className="mx-auto max-w-7xl px-4 py-6 sm:px-6">{active==="dashboard"&&<><div className="mb-6"><h2 className="text-xl font-semibold">Monthly overview</h2><p className="text-sm text-zinc-500">Your current financial picture, with explainable numbers.</p></div>{loading?<p className="text-zinc-500">Loading dashboard…</p>:error?<div className="rounded-2xl border border-red-900 bg-red-950/30 p-5 text-red-200">{error}</div>:<Dashboard data={data}/>}</>}{active!=="dashboard"&&<section className="rounded-2xl border border-zinc-800 bg-zinc-900/70 p-6"><h2 className="text-xl font-semibold capitalize">{active.replace("-"," ")}</h2><p className="mt-2 text-zinc-400">This module is connected to the Financial-D3v product navigation and will progressively expose the validated API workflows.</p></section>}<div className="mt-8 rounded-2xl border border-zinc-800 bg-zinc-900/40 p-5"><p className="text-xs uppercase tracking-wider text-zinc-500">Local owner</p><input value={ownerId} onChange={e=>setOwnerId(e.target.value)} className="mt-2 w-full rounded-xl border border-zinc-700 bg-zinc-950 px-4 py-3 outline-none focus:border-zinc-400" aria-label="Local owner id"/><p className="mt-2 text-xs text-zinc-600">Local development fallback only. Firebase Auth remains the production identity path.</p></div></main></div>
}
export default App;
