import { useEffect, useMemo, useState } from "react";
import { api } from "./api";

const money = (m) => new Intl.NumberFormat("es-CO",{style:"currency",currency:m?.currency||"COP",maximumFractionDigits:0}).format((Number(m?.minorUnits)||0)/100);
const toMinor = (value) => Math.round(Number(value||0)*100);
const today = new Date();
const monthStart = new Date(today.getFullYear(),today.getMonth(),1).toISOString();
const monthEnd = new Date(today.getFullYear(),today.getMonth()+1,1).toISOString();

const nav = [
  ["dashboard","Overview","⌂"],["transactions","Transactions","↕"],["accounts","Accounts","▣"],
  ["budget","Budget","◫"],["savings","Savings","◎"],["debts","Debts","◇"],
  ["net-worth","Net worth","◆"],["education","Education","?"]
];
const accountTypes = [["cash","Cash"],["bank","Bank"],["credit","Credit"],["investment","Investment"],["other","Other"]];
const transactionTypes = [["expense","Expense"],["income","Income"],["transfer","Transfer"]];

function Button({children,onClick,primary=false,disabled=false,type="button"}){return <button type={type} disabled={disabled} onClick={onClick} className={primary?"button primary":"button"}>{children}</button>}
function Input({label,...props}){return <label className="field"><span>{label}</span><input {...props}/></label>}
function Select({label,children,...props}){return <label className="field"><span>{label}</span><select {...props}>{children}</select></label>}
function Panel({children,className=""}){return <section className={"panel "+className}>{children}</section>}
function Loading(){return <div className="state">Loading your financial workspace…</div>}
function Empty({title,text}){return <div className="empty"><b>+</b><h3>{title}</h3><p>{text}</p></div>}
function Notice({error,onRetry}){return error?<div className="notice error"><b>Something needs attention.</b><span>{error}</span>{onRetry&&<Button onClick={onRetry}>Try again</Button>}</div>:null}
function Metric({label,value,detail,icon}){return <article className="metric"><div><small>{label}</small><span>{icon}</span></div><strong>{value}</strong><em>{detail}</em></article>}

function Sidebar({active,setActive}){return <aside className="sidebar"><div className="brand"><b className="brand-mark">F</b><div><strong>Financial-D3v</strong><small>Personal finance</small></div></div><span className="label">Workspace</span><nav>{nav.map(([key,label,icon])=><button key={key} onClick={()=>setActive(key)} className={active===key?"nav active":"nav"}><i>{icon}</i>{label}</button>)}</nav><div className="side-bottom"><div className="privacy"><span/><div><b>Private workspace</b><small>Your data stays yours.</small></div></div><small className="signature">PALMI-D3V · v0.1</small></div></aside>}
function MobileNav({active,setActive}){return <nav className="mobile-nav">{nav.slice(0,5).map(([key,label,icon])=><button key={key} onClick={()=>setActive(key)} className={active===key?"active":""}><i>{icon}</i><small>{label}</small></button>)}</nav>}
function Header({active,refresh,loading}){const label=nav.find(x=>x[0]===active)?.[1]||"Overview";return <header className="topbar"><div><small>Financial-D3v <b>/</b> {label}</small><h1>{label}</h1></div><div className="top-actions"><span className="status"><i/> Local mode</span><Button onClick={refresh}>{loading?"Refreshing…":"Refresh"}</Button><b className="avatar">P</b></div></header>}

function Dashboard({data,setActive}){
 const s=data?.summary;
 const income=Number(s?.income?.minorUnits)||0, expenses=Number(s?.expenses?.minorUnits)||0, max=Math.max(income,expenses,1);
 return <><section className="hero"><div><small>Your financial picture</small><h2>Make your money <em>make sense.</em></h2><p>Record the movement, understand the state, then decide what comes next.</p></div><Button primary onClick={()=>setActive("transactions")}>＋ Record movement</Button></section>
 <div className="metrics"><Metric label="Income" value={money(s?.income)} detail="Money in this month" icon="↗"/><Metric label="Expenses" value={money(s?.expenses)} detail="Money out this month" icon="↘"/><Metric label="Net cash flow" value={money(s?.netCashFlow)} detail="Income minus expenses" icon="≈"/><Metric label="Net worth" value={money(s?.netWorth?.net)} detail="Assets minus liabilities" icon="◆"/></div>
 <div className="two-col"><Panel><div className="panel-head"><div><small>Monthly cash flow</small><h2>Where your money moved</h2></div></div><div className="flow-row">{[["Income",income,s?.income,"↗"],["Expenses",expenses,s?.expenses,"↘"]].map(([label,value,amount,icon])=><div className="flow" key={label}><div><label>{label}</label><b>{money(amount)}</b></div><div className="track"><i style={{width:`${Math.max((value/max)*100,value?8:0)}%`}}/></div></div>)}</div></Panel><Panel className="education"><span className="badge">Learn</span><small>Financial education</small><h2>Your numbers should teach you something.</h2><p>Financial-D3v connects the number with the reason behind it, then turns that understanding into your next action.</p><div>FACT <b>→</b> CALCULATION <b>→</b> INTERPRETATION <b>→</b> ACTION</div></Panel></div>
 <section><div className="section-head"><div><small>Next actions</small><h2>Keep the loop moving</h2></div></div><div className="actions">{[["transactions","Add transaction","Record money in or out"],["accounts","Manage accounts","See where money lives"],["budget","Review budget","Compare planned vs actual"]].map(([key,title,detail])=><button key={key} onClick={()=>setActive(key)}><b>+</b><div><strong>{title}</strong><small>{detail}</small></div><i>↗</i></button>)}</div></section></>
}

function Transactions({ownerId}){
 const [accounts,setAccounts]=useState([]),[categories,setCategories]=useState([]),[items,setItems]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [form,setForm]=useState({type:"expense",amount:"",accountId:"",categoryId:"",description:"",occurredAt:new Date().toISOString().slice(0,16)});
 const load=async()=>{setLoading(true);setError("");try{const [a,c,t]=await Promise.all([api("/api/v1/accounts",{ownerId}),api("/api/v1/categories",{ownerId}),api(`/api/v1/transactions?start=${encodeURIComponent(monthStart)}&end=${encodeURIComponent(monthEnd)}`,{ownerId})]);setAccounts(a||[]);setCategories(c||[]);setItems(t||[]);if(!form.accountId&&a?.[0])setForm(f=>({...f,accountId:a[0].id||a[0].ID}))}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const filtered=categories.filter(c=>(c.kind||c.Kind)===form.type);
 const submit=async(e)=>{e.preventDefault();setSaving(true);setError("");setMessage("");try{const account=accounts.find(a=>(a.id||a.ID)===form.accountId);if(!account)throw new Error("Select an account.");const currency=account.currency||account.Currency||"COP";await api("/api/v1/transactions",{ownerId,method:"POST",body:{accountId:form.accountId,type:form.type,minorUnits:toMinor(form.amount),currency,categoryId:form.type==="transfer"?"":form.categoryId,description:form.description,occurredAt:new Date(form.occurredAt).toISOString()}});setForm(f=>({...f,amount:"",description:""}));setMessage("Transaction recorded.");await load()}catch(e){setError(e.message)}finally{setSaving(false)}};
 return <div className="workspace"><div className="module-head"><div><small>Record → Categorize</small><h2>Transactions</h2><p>Capture money in, money out, and transfers without slowing down the workflow.</p></div></div><div className="two-col"><Panel><div className="panel-head"><div><small>Quick entry</small><h3>Record a movement</h3></div></div><form onSubmit={submit} className="form-grid"><Select label="Type" value={form.type} onChange={e=>setForm({...form,type:e.target.value,categoryId:""})}>{transactionTypes.map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select><Input label="Amount" type="number" min="0.01" step="0.01" required value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><Select label="Account" value={form.accountId} onChange={e=>setForm({...form,accountId:e.target.value})}><option value="">Select account</option>{accounts.map(a=><option key={a.id||a.ID} value={a.id||a.ID}>{a.name||a.Name}</option>)}</Select>{form.type!=="transfer"&&<Select label="Category" value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Select category</option>{filtered.map(c=><option key={c.id||c.ID} value={c.id||c.ID}>{c.name||c.Name}</option>)}</Select>}<Input label="Date" type="datetime-local" value={form.occurredAt} onChange={e=>setForm({...form,occurredAt:e.target.value})}/><Input label="Description" placeholder="Optional note" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><div className="form-actions"><Button primary disabled={saving} type="submit">{saving?"Saving…":"Record transaction"}</Button></div></form><Notice error={error}/>{message&&<div className="notice success">{message}</div>}</Panel><Panel><div className="panel-head"><div><small>This month</small><h3>Recent movements</h3></div></div>{loading?<Loading/>:items.length===0?<Empty title="No transactions yet" text="Record your first movement and the dashboard will start learning from your ledger."/>:<div className="list">{items.slice().reverse().map(t=><div className="list-row" key={t.id||t.ID}><div><b>{t.description||t.Description||"Transaction"}</b><small>{t.type||t.Type} · {new Date(t.occurredAt||t.OccurredAt).toLocaleDateString("es-CO")}</small></div><strong className={(t.type||t.Type)==="expense"?"negative":"positive"}>{(t.type||t.Type)==="expense"?"−":"+"}{money(t.amount||t.Amount)}</strong></div>)}</div>}</Panel></div></div>
}

function Accounts({ownerId}){
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[form,setForm]=useState({name:"",type:"bank",currency:"COP",opening:""});
 const load=async()=>{setLoading(true);setError("");try{const accounts=await api("/api/v1/accounts",{ownerId})||[];const enriched=await Promise.all(accounts.map(async a=>{const accountId=a.id||a.ID;try{return {...a,balance:await api(`/api/v1/accounts/${accountId}/balance`,{ownerId})}}catch{return a}}));setItems(enriched)}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const submit=async(e)=>{e.preventDefault();setSaving(true);setError("");try{await api("/api/v1/accounts",{ownerId,method:"POST",body:{name:form.name,type:form.type,currency:form.currency.toUpperCase(),openingMinorUnits:toMinor(form.opening)}});setForm({name:"",type:"bank",currency:"COP",opening:""});await load()}catch(e){setError(e.message)}finally{setSaving(false)}};
 return <div className="workspace"><div className="module-head"><div><small>Foundation</small><h2>Accounts</h2><p>Know where your money lives. Balances remain derived from the authoritative ledger.</p></div></div><div className="two-col"><Panel><div className="panel-head"><div><small>New account</small><h3>Add an account</h3></div></div><form onSubmit={submit} className="form-grid"><Input label="Name" placeholder="Main bank account" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Select label="Type" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{accountTypes.map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select><Input label="Currency" maxLength="3" value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}/><Input label="Opening balance" type="number" step="0.01" value={form.opening} onChange={e=>setForm({...form,opening:e.target.value})}/><div className="form-actions"><Button primary disabled={saving} type="submit">{saving?"Saving…":"Create account"}</Button></div></form><Notice error={error}/></Panel><Panel><div className="panel-head"><div><small>Your money</small><h3>Accounts</h3></div></div>{loading?<Loading/>:items.length===0?<Empty title="No accounts yet" text="Create your first cash or bank account to start recording transactions."/>:<div className="account-grid">{items.map(a=><article className="account-card" key={a.id||a.ID}><div><span className="badge">{a.type||a.Type}</span><small>{a.currency||a.Currency}</small></div><h3>{a.name||a.Name}</h3><strong>{money(a.balance||a.Balance||a.openingBalance||a.OpeningBalance)}</strong><p>Opening balance {money(a.openingBalance||a.OpeningBalance)}</p></article>)}</div>}</Panel></div></div>
}

function Budget({ownerId}){
 const [categories,setCategories]=useState([]),[budgets,setBudgets]=useState([]),[selected,setSelected]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[form,setForm]=useState({name:"Monthly budget",items:[{categoryId:"",limit:""}]});
 const load=async()=>{setLoading(true);setError("");try{const [c,b]=await Promise.all([api("/api/v1/categories",{ownerId}),api(`/api/v1/budgets?start=${encodeURIComponent(monthStart)}&end=${encodeURIComponent(monthEnd)}`,{ownerId})]);setCategories((c||[]).filter(x=>(x.kind||x.Kind)==="expense"));setBudgets(b||[])}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const setItem=(i,k,v)=>setForm(f=>({...f,items:f.items.map((x,n)=>n===i?{...x,[k]:v}:x)}));
 const createBudget=async(e)=>{e.preventDefault();setSaving(true);setError("");try{const items=form.items.filter(x=>x.categoryId&&Number(x.limit)>0).map(x=>({categoryId:x.categoryId,limitMinorUnits:toMinor(x.limit)}));if(!items.length)throw new Error("Add at least one expense category.");if(new Set(items.map(x=>x.categoryId)).size!==items.length)throw new Error("Each category can appear only once.");await api("/api/v1/budgets",{ownerId,method:"POST",body:{name:form.name,currency:"COP",startDate:monthStart,endDate:monthEnd,items}});setForm({name:"Monthly budget",items:[{categoryId:"",limit:""}]});await load()}catch(e){setError(e.message)}finally{setSaving(false)}};
 const open=async(b)=>{try{setSelected(await api(`/api/v1/budgets/${b.id||b.ID}/summary`,{ownerId}))}catch(e){setError(e.message)}};
 return <div className="workspace"><div className="module-head"><div><small>Plan → Understand</small><h2>Budget</h2><p>Set limits, then compare them with actual spending from the transaction ledger.</p></div></div><div className="two-col"><Panel><div className="panel-head"><div><small>Monthly plan</small><h3>Create a budget</h3></div></div><form onSubmit={createBudget} className="form-grid"><Input label="Budget name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><div className="budget-items">{form.items.map((item,index)=><div className="budget-input-row" key={index}><Select label={`Category ${index+1}`} required value={item.categoryId} onChange={e=>setItem(index,"categoryId",e.target.value)}><option value="">Select category</option>{categories.map(c=><option key={c.id||c.ID} value={c.id||c.ID}>{c.name||c.Name}</option>)}</Select><Input label="Limit" type="number" min="0.01" step="0.01" required value={item.limit} onChange={e=>setItem(index,"limit",e.target.value)}/></div>)}</div><div className="form-actions"><Button primary disabled={saving} type="submit">{saving?"Saving…":"Create budget"}</Button></div></form><Notice error={error}/></Panel><Panel><div className="panel-head"><div><small>Planned vs actual</small><h3>Budget overview</h3></div></div>{loading?<Loading/>:budgets.length===0?<Empty title="No budget yet" text="Create a monthly budget and give your expense categories a clear job."/>:<div className="list">{budgets.map(b=><button className="list-row clickable" key={b.id||b.ID} onClick={()=>open(b)}><div><b>{b.name||b.Name}</b><small>{b.currency||b.Currency}</small></div><strong>{money({minorUnits:(b.items||b.Items||[]).reduce((sum,item)=>sum+(item.limitMinorUnits||item.LimitMinorUnits||item.limit?.minorUnits||item.Limit?.MinorUnits||0),0),currency:b.currency||b.Currency||"COP"})}</strong></button>)}</div>}</Panel></div>{selected&&<Panel className="budget-detail"><div className="panel-head"><div><small>FACT → CALCULATION</small><h3>Budget summary</h3></div><Button onClick={()=>setSelected(null)}>Close</Button></div><div className="metrics"><Metric label="Planned" value={money(selected.totalLimit||selected.TotalLimit)} detail="Budget limit" icon="◫"/><Metric label="Spent" value={money(selected.totalSpent||selected.TotalSpent)} detail="Authoritative ledger" icon="↘"/><Metric label="Remaining" value={money(selected.totalRemaining||selected.TotalRemaining)} detail="Limit minus spent" icon="≈"/></div></Panel>}</div>
}

function NetWorth({ownerId}){const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=async()=>{setLoading(true);setError("");try{setData(await api("/api/v1/net-worth?currency=COP",{ownerId}))}catch(e){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);return <div className="workspace"><div className="module-head"><div><small>Understand → Review</small><h2>Net worth</h2><p>See your financial position from backend-authoritative assets and liabilities.</p></div></div>{loading?<Loading/>:error?<Notice error={error} onRetry={load}/>:<><div className="metrics"><Metric label="Net worth" value={money(data?.net)} detail="Assets minus liabilities" icon="◆"/><Metric label="Assets" value={money(data?.assets)} detail="Tracked assets" icon="↗"/><Metric label="Liabilities" value={money(data?.liabilities)} detail="All liabilities" icon="↘"/><Metric label="Debt" value={money(data?.debtLiabilities)} detail="Debt balance included" icon="◇"/></div><Panel className="education"><span className="badge">FACT → CALCULATION → INTERPRETATION → ACTION</span><p><b>Fact:</b> these values come from the financial position service.</p><p><b>Calculation:</b> net worth = assets − liabilities.</p><p><b>Interpretation:</b> the result is a snapshot, not a forecast.</p><p><b>Action:</b> review the components and keep the ledger current.</p></Panel></>}</div>}

function Education({ownerId}){const [cards,setCards]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=async()=>{setLoading(true);setError("");try{setCards(await api("/api/v1/education",{ownerId})||[])}catch(e){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);return <div className="workspace"><div className="module-head"><div><small>Learn → Adjust</small><h2>Education</h2><p>Learn financial concepts through explicit facts, calculations, interpretations and actions.</p></div></div>{loading?<Loading/>:error?<Notice error={error} onRetry={load}/>:cards.length===0?<Empty title="No education cards" text="Education content will appear here as the learning workspace evolves."/>:<div className="education-grid">{cards.map(card=><Panel className="education" key={card.id||card.ID}><span className="badge">{card.topic||card.Topic}</span><h3>{card.title||card.Title}</h3><div className="edu-step"><b>FACT</b><p>{card.fact||card.Fact}</p></div><div className="edu-step"><b>CALCULATION</b><p>{card.calculation||card.Calculation}</p></div><div className="edu-step"><b>INTERPRETATION</b><p>{card.interpretation||card.Interpretation}</p></div><div className="edu-step"><b>ACTION</b><p>{card.action||card.Action}</p></div></Panel>)}</div>}</div>}


function Savings({ownerId}){
 const [goals,setGoals]=useState([]),[selected,setSelected]=useState(null),[accounts,setAccounts]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [form,setForm]=useState({name:"",target:"",currency:"COP",targetDate:""}),[contribution,setContribution]=useState({amount:"",sourceAccountId:"",note:""});
 const load=async()=>{setLoading(true);setError("");try{const [g,a]=await Promise.all([api("/api/v1/savings-goals",{ownerId}),api("/api/v1/accounts",{ownerId})]);setGoals(g||[]);setAccounts(a||[]);if(!selected&&g?.[0])await open(g[0])}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const open=async(g)=>{try{setSelected(await api("/api/v1/savings-goals/"+(g.id||g.ID)+"/summary",{ownerId}))}catch(e){setError(e.message)}};
 const create=async(e)=>{e.preventDefault();setSaving(true);setError("");setMessage("");try{if(toMinor(form.target)<=0)throw new Error("Target amount must be greater than zero.");await api("/api/v1/savings-goals",{ownerId,method:"POST",body:{name:form.name,targetMinorUnits:toMinor(form.target),currency:form.currency.toUpperCase(),targetDate:form.targetDate?new Date(form.targetDate+"T23:59:59").toISOString():""}});setForm({name:"",target:"",currency:"COP",targetDate:""});setMessage("Savings goal created.");await load()}catch(e){setError(e.message)}finally{setSaving(false)}};
 const addContribution=async(e)=>{e.preventDefault();if(!selected)return;setSaving(true);setError("");setMessage("");try{const goal=selected.goal||selected.Goal||selected;if(toMinor(contribution.amount)<=0)throw new Error("Contribution must be greater than zero.");await api("/api/v1/savings-goals/"+(goal.id||goal.ID)+"/contributions",{ownerId,method:"POST",body:{amountMinorUnits:toMinor(contribution.amount),currency:goal.target?.currency||goal.Target?.Currency||goal.currency||goal.Currency||"COP",sourceAccountId:contribution.sourceAccountId,transactionId:"",contributedAt:new Date().toISOString(),note:contribution.note}});setContribution({amount:"",sourceAccountId:"",note:""});setMessage("Contribution recorded.");await load()}catch(e){setError(e.message)}finally{setSaving(false)}};
 const goal=selected?.goal||selected?.Goal||selected,progress=selected?.progress||selected?.Progress||selected,history=selected?.contributions||selected?.Contributions||[];
 return <div className="workspace"><div className="module-head"><div><small>Plan → Save → Review</small><h2>Savings</h2><p>Make saving visible without turning contributions into ordinary expenses.</p></div></div>
 <div className="two-col"><Panel><div className="panel-head"><div><small>New goal</small><h3>Create a savings goal</h3></div></div><form onSubmit={create} className="form-grid"><Input label="Goal name" placeholder="Emergency fund" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Input label="Target amount" type="number" min="0.01" step="0.01" required value={form.target} onChange={e=>setForm({...form,target:e.target.value})}/><Input label="Currency" maxLength="3" value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}/><Input label="Target date" type="date" value={form.targetDate} onChange={e=>setForm({...form,targetDate:e.target.value})}/><div className="form-actions"><Button primary disabled={saving} type="submit">{saving?"Saving…":"Create goal"}</Button></div></form></Panel>
 <Panel><div className="panel-head"><div><small>Your goals</small><h3>Savings progress</h3></div></div>{loading?<Loading/>:goals.length===0?<Empty title="No savings goals yet" text="Create a goal and turn future contributions into visible progress."/>:<div className="list">{goals.map(g=><button className="list-row clickable" key={g.id||g.ID} onClick={()=>open(g)}><div><b>{g.name||g.Name}</b><small>{money(g.target||g.Target)}</small></div><strong>View</strong></button>)}</div>}</Panel></div>
 {goal&&<div className="two-col"><Panel><div className="panel-head"><div><small>Goal detail</small><h3>{goal.name||goal.Name}</h3></div></div><div className="metrics"><Metric label="Target" value={money(goal.target||goal.Target)} detail="Chosen goal" icon="◎"/><Metric label="Saved" value={money(progress.contributed||progress.Contributed)} detail="Goal-progress records" icon="↗"/><Metric label="Remaining" value={money(progress.remaining||progress.Remaining)} detail="Target minus saved" icon="≈"/><Metric label="Progress" value={(Number(progress.percentage||progress.Percentage||0)).toFixed(0)+"%"} detail="Completion" icon="%"/></div><div className="notice"><b>FACT</b><span>Target and contributions are recorded financial data.</span><b>CALCULATION</b><span>Remaining and percentage come from the savings summary.</span><b>INTERPRETATION</b><span>Progress shows how far the chosen target has advanced.</span><b>ACTION</b><span>Choose a contribution pattern that fits your plan.</span></div>{(progress.requiredPerDay||progress.RequiredPerDay)?.minorUnits!==undefined&&<div className="notice"><b>Required pace</b><span>{money(progress.requiredPerDay||progress.RequiredPerDay)} per day · {Number(progress.daysRemaining||progress.DaysRemaining||0)} days remaining.</span></div>}</Panel>
 <Panel><div className="panel-head"><div><small>Continue the habit</small><h3>Add contribution</h3></div></div><form onSubmit={addContribution} className="form-grid"><Input label="Amount" type="number" min="0.01" step="0.01" required value={contribution.amount} onChange={e=>setContribution({...contribution,amount:e.target.value})}/><Select label="Source account (optional)" value={contribution.sourceAccountId} onChange={e=>setContribution({...contribution,sourceAccountId:e.target.value})}><option value="">No source account</option>{accounts.map(a=><option key={a.id||a.ID} value={a.id||a.ID}>{a.name||a.Name}</option>)}</Select><Input label="Note" placeholder="Optional" value={contribution.note} onChange={e=>setContribution({...contribution,note:e.target.value})}/><div className="form-actions"><Button primary disabled={saving} type="submit">{saving?"Saving…":"Record contribution"}</Button></div></form><div className="panel-head" style={{marginTop:22}}><div><small>History</small><h3>Contributions</h3></div></div>{history.length===0?<Empty title="No contributions yet" text="The goal ledger will appear here after the first contribution."/>:<div className="list">{history.slice().reverse().map(c=><div className="list-row" key={c.id||c.ID}><div><b>{money(c.amount||c.Amount)}</b><small>{new Date(c.contributedAt||c.ContributedAt).toLocaleDateString("es-CO")} · {c.note||c.Note||"Contribution"}</small></div><strong>+</strong></div>)}</div>}</Panel></div>}
 {error&&<Notice error={error}/>} {message&&<div className="notice success">{message}</div>}</div>
}

function Debts({ownerId}){
 const [items,setItems]=useState([]),[selected,setSelected]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [form,setForm]=useState({name:"",original:"",balance:"",minimum:"",rate:"",currency:"COP"}),[payment,setPayment]=useState({amount:"",principal:"",interest:"",fees:"",note:""});
 const load=async()=>{setLoading(true);setError("");try{const d=await api("/api/v1/debts",{ownerId});setItems(d||[]);if(!selected&&d?.[0])await open(d[0])}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const open=async(d)=>{try{setSelected(await api("/api/v1/debts/"+(d.id||d.ID)+"/summary",{ownerId}))}catch(e){setError(e.message)}};
 const create=async(e)=>{e.preventDefault();setSaving(true);setError("");setMessage("");try{const original=toMinor(form.original),balance=toMinor(form.balance),minimum=toMinor(form.minimum);if(original<=0||balance<0||balance>original)throw new Error("Debt balance must be between zero and the original principal.");await api("/api/v1/debts",{ownerId,method:"POST",body:{name:form.name,originalPrincipalMinorUnits:original,balanceMinorUnits:balance,minimumPaymentMinorUnits:minimum,currency:form.currency.toUpperCase(),annualRateBPS:Math.round(Number(form.rate||0)*100)}});setForm({name:"",original:"",balance:"",minimum:"",rate:"",currency:"COP"});setMessage("Debt created.");await load()}catch(e){setError(e.message)}finally{setSaving(false)}};
 const pay=async(e)=>{e.preventDefault();if(!selected)return;setSaving(true);setError("");setMessage("");try{const debt=selected.debt||selected.Debt,amount=toMinor(payment.amount),principal=toMinor(payment.principal),interest=toMinor(payment.interest),fees=toMinor(payment.fees);if(amount<=0||amount!==principal+interest+fees)throw new Error("Payment total must equal principal + interest + fees.");await api("/api/v1/debts/"+(debt.id||debt.ID)+"/payments",{ownerId,method:"POST",body:{amountMinorUnits:amount,principalMinorUnits:principal,interestMinorUnits:interest,feesMinorUnits:fees,currency:debt.balance?.currency||debt.Balance?.Currency||"COP",paidAt:new Date().toISOString(),note:payment.note}});setPayment({amount:"",principal:"",interest:"",fees:"",note:""});setMessage("Debt payment recorded.");await load()}catch(e){setError(e.message)}finally{setSaving(false)}};
 const debt=selected?.debt||selected?.Debt,payments=selected?.payments||selected?.Payments||[],totalPaid=selected?.totalPaid||selected?.TotalPaid;
 return <div className="workspace"><div className="module-head"><div><small>Understand → Adjust</small><h2>Debts</h2><p>Make obligations transparent and show exactly how each payment changes the balance.</p></div></div>
 <div className="two-col"><Panel><div className="panel-head"><div><small>New debt</small><h3>Add an obligation</h3></div></div><form onSubmit={create} className="form-grid"><Input label="Name" placeholder="Credit card" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Input label="Original principal" type="number" min="0.01" step="0.01" required value={form.original} onChange={e=>setForm({...form,original:e.target.value})}/><Input label="Current balance" type="number" min="0" step="0.01" required value={form.balance} onChange={e=>setForm({...form,balance:e.target.value})}/><Input label="Minimum payment" type="number" min="0" step="0.01" value={form.minimum} onChange={e=>setForm({...form,minimum:e.target.value})}/><Input label="Annual rate (%)" type="number" min="0" step="0.01" value={form.rate} onChange={e=>setForm({...form,rate:e.target.value})}/><Input label="Currency" maxLength="3" value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}/><div className="form-actions"><Button primary disabled={saving} type="submit">{saving?"Saving…":"Create debt"}</Button></div></form></Panel>
 <Panel><div className="panel-head"><div><small>Your obligations</small><h3>Debt overview</h3></div></div>{loading?<Loading/>:items.length===0?<Empty title="No debts yet" text="Add an obligation to make its balance and payment composition visible."/>:<div className="list">{items.map(d=><button className="list-row clickable" key={d.id||d.ID} onClick={()=>open(d)}><div><b>{d.name||d.Name}</b><small>{d.status||d.Status} · {money(d.balance||d.Balance)}</small></div><strong>{money(d.minimumPayment||d.MinimumPayment)}</strong></button>)}</div>}</Panel></div>
 {debt&&<div className="two-col"><Panel><div className="panel-head"><div><small>Debt detail</small><h3>{debt.name||debt.Name}</h3></div></div><div className="metrics"><Metric label="Original" value={money(debt.originalPrincipal||debt.OriginalPrincipal)} detail="Original principal" icon="◎"/><Metric label="Balance" value={money(debt.balance||debt.Balance)} detail="Backend-authoritative" icon="◇"/><Metric label="Minimum" value={money(debt.minimumPayment||debt.MinimumPayment)} detail="Minimum payment" icon="≈"/><Metric label="Paid" value={money(totalPaid)} detail="Recorded payment totals" icon="↘"/></div><div className="notice"><b>FACT</b><span>Debt balance and payment records come from the backend.</span><b>CALCULATION</b><span>Only principal reduces the outstanding debt balance.</span><b>INTERPRETATION</b><span>Interest and fees explain payment composition; they are not principal.</span><b>ACTION</b><span>Review the balance and choose the next payment intentionally.</span></div></Panel>
 <Panel><div className="panel-head"><div><small>Payment entry</small><h3>Record payment</h3></div></div><div className="notice"><b>Validation</b><span>Total must equal principal + interest + fees.</span></div><form onSubmit={pay} className="form-grid"><Input label="Total payment" type="number" min="0.01" step="0.01" required value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/><Input label="Principal" type="number" min="0" step="0.01" required value={payment.principal} onChange={e=>setPayment({...payment,principal:e.target.value})}/><Input label="Interest" type="number" min="0" step="0.01" required value={payment.interest} onChange={e=>setPayment({...payment,interest:e.target.value})}/><Input label="Fees" type="number" min="0" step="0.01" required value={payment.fees} onChange={e=>setPayment({...payment,fees:e.target.value})}/><Input label="Note" placeholder="Optional" value={payment.note} onChange={e=>setPayment({...payment,note:e.target.value})}/><div className="form-actions"><Button primary disabled={saving} type="submit">{saving?"Saving…":"Record payment"}</Button></div></form></Panel></div>}
 <div className="panel-head" style={{marginTop:22}}><div><small>History</small><h3>Payments</h3></div></div>{debt&&(payments.length===0?<Empty title="No payments yet" text="Payment history will appear here after the first payment."/>:<div className="list">{payments.slice().reverse().map(p=><div className="list-row" key={p.id||p.ID}><div><b>{money(p.amount||p.Amount)}</b><small>Principal {money(p.principal||p.Principal)} · Interest {money(p.interest||p.Interest)} · Fees {money(p.fees||p.Fees)}</small></div><strong>{new Date(p.paidAt||p.PaidAt).toLocaleDateString("es-CO")}</strong></div>)}</div>)}
 {error&&<Notice error={error}/>} {message&&<div className="notice success">{message}</div>}</div>
}


function Placeholder({active,setActive}){const item=nav.find(n=>n[0]===active);return <div className="module"><small>Workspace</small><h2>{item?.[1]}</h2><p>This product surface is reserved for its validated workflow.</p><Panel className="empty"><b>{item?.[2]}</b><h3>{item?.[1]} is part of the financial learning loop.</h3><p>Continue with the next validated product iteration without changing the financial source of truth.</p><Button onClick={()=>setActive("dashboard")}>Back to overview</Button></Panel></div>}

export default function App(){
 const [active,setActive]=useState("dashboard"),[ownerId]=useState(localStorage.getItem("financial_owner")||"local-owner"),[data,setData]=useState(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const period=useMemo(()=>`start=${encodeURIComponent(monthStart)}&end=${encodeURIComponent(monthEnd)}&currency=COP`,[]);
 const load=async()=>{setLoading(true);setError("");try{setData(await api(`/api/v1/dashboard?${period}`,{ownerId}))}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{localStorage.setItem("financial_owner",ownerId);load()},[]);
 const content=active==="dashboard"?<Dashboard data={data} setActive={setActive}/>:active==="transactions"?<Transactions ownerId={ownerId}/>:active==="accounts"?<Accounts ownerId={ownerId}/>:active==="budget"?<Budget ownerId={ownerId}/>:active==="savings"?<Savings ownerId={ownerId}/>:active==="debts"?<Debts ownerId={ownerId}/>:active==="net-worth"?<NetWorth ownerId={ownerId}/>:active==="education"?<Education ownerId={ownerId}/>:<Placeholder active={active} setActive={setActive}/>;
 return <div className="shell"><Sidebar active={active} setActive={setActive}/><div className="main"><Header active={active} refresh={load} loading={loading}/><main>{active==="dashboard"?(loading?<Loading/>:error?<Notice error={error} onRetry={load}/>:content):content}<footer>Private by design · Financial-D3v · PALMI-D3V</footer></main></div><MobileNav active={active} setActive={setActive}/></div>
}