package application

import("context";"testing";"time";"github.com/palmid3v/financial-d3v-palmid3v/internal/domain";"github.com/palmid3v/financial-d3v-palmid3v/internal/persistence")
type fakeAccounts struct{values map[string]domain.Account}
func(f *fakeAccounts)Create(_ context.Context,a domain.Account)error{f.values[a.ID]=a;return nil}
func(f *fakeAccounts)Get(_ context.Context,owner,id string)(domain.Account,error){a,ok:=f.values[id];if !ok||a.OwnerID!=owner{return domain.Account{},persistence.ErrNotFound};return a,nil}
func(f *fakeAccounts)List(_ context.Context,owner string)([]domain.Account,error){var out []domain.Account;for _,a:=range f.values{if a.OwnerID==owner{out=append(out,a)}};return out,nil}
type fakeTransactions struct{values map[string]domain.Transaction}
func(f *fakeTransactions)Create(_ context.Context,v domain.Transaction)error{f.values[v.ID]=v;return nil}
func(f *fakeTransactions)Get(_ context.Context,owner,id string)(domain.Transaction,error){v,ok:=f.values[id];if !ok||v.OwnerID!=owner{return domain.Transaction{},persistence.ErrNotFound};return v,nil}
func(f *fakeTransactions)ListByAccount(_ context.Context,owner,account string)([]domain.Transaction,error){var out []domain.Transaction;for _,v:=range f.values{if v.OwnerID==owner&&v.AccountID==account{out=append(out,v)}};return out,nil}
func(f *fakeTransactions)ListByPeriod(_ context.Context,owner string,p domain.FinancialPeriod)([]domain.Transaction,error){var out []domain.Transaction;for _,v:=range f.values{if v.OwnerID==owner&&p.Contains(v.OccurredAt){out=append(out,v)}};return out,nil}
func TestTransactionServiceRejectsCurrencyMismatch(t *testing.T){a:=&fakeAccounts{values:map[string]domain.Account{}};tx:=&fakeTransactions{values:map[string]domain.Transaction{}};account,_:=domain.NewAccount("a1","owner","Bank",domain.AccountTypeBank,domain.Money{MinorUnits:1000,Currency:"COP"},time.Now());a.values["a1"]=account;value,_:=domain.NewTransaction("t1","owner","a1",domain.TransactionExpense,domain.Money{MinorUnits:500,Currency:"USD"},time.Now());if err:=NewTransactionService(tx,a).Create(context.Background(),value);err==nil{t.Fatal("expected currency mismatch")}}
func TestAccountServiceCalculatesBalanceFromLedger(t *testing.T){a:=&fakeAccounts{values:map[string]domain.Account{}};tx:=&fakeTransactions{values:map[string]domain.Transaction{}};account,_:=domain.NewAccount("a1","owner","Bank",domain.AccountTypeBank,domain.Money{MinorUnits:10000,Currency:"COP"},time.Now());a.values["a1"]=account;income,_:=domain.NewTransaction("t1","owner","a1",domain.TransactionIncome,domain.Money{MinorUnits:5000,Currency:"COP"},time.Now());expense,_:=domain.NewTransaction("t2","owner","a1",domain.TransactionExpense,domain.Money{MinorUnits:1500,Currency:"COP"},time.Now());tx.values["t1"]=income;tx.values["t2"]=expense;balance,err:=NewAccountService(a,tx).Balance(context.Background(),"owner","a1");if err!=nil{t.Fatal(err)};if balance.MinorUnits!=13500{t.Fatalf("got %d, want 13500",balance.MinorUnits)}}
